### ISSUE TITLE
[ED] Global legal suits?

### ISSUE THREAD

**Issue by vavroom** [w3c/wai-bcase#19]
> Other than a few actions based on the Americans with Disabilities Act (ADA) in the United States, and Section 508 of the Rehabilitation Act for US government entities, there was little evidence of substantial global legal effort related to accessibility.

Is it worth mentioning the 2000 Sydney olympics site, which was probably/arguably the case that brought  accessibility to mind for many people?

**Comment by sharronrush** [comment]
Rewritten to read:
For much of the first decade of the 21st Century, the legal risk was seen to be relatively small for maintaining an inaccessible web site. In the early 2000s, there were a few legal actions based on the Americans with Disabilities Act (ADA) in the United States, and Section 508 of the Rehabilitation Act for US government entities. Most notable perhaps was the complaint put to the Human Rights and Equal Opportunities Commission (HREOC) in 2000 that the website of the Sydney Olympics was inaccessible according to the Commonwealth Disability Discrimination Act 1992 (Cth DDA). These were encouraging initiatives but otherwise there was little evidence of substantial global legal effort related to accessibility. Despite several encouraging victories in US courts for people with disabilities seeking equal access, Section 508 was seen to have limited scope and the ADA was unevenly applied by various courts.

**Comment by slhenry** [comment]
Here is a reference for the Sydney Olympics case: <https://www.w3.org/WAI/bcase/socog-case-study>

**Comment by sharronrush** [comment]
Hey Shawn,

What is your recommendation for use of this? Just trying to understand action needed to close the issue.

**Comment by slhenry** [comment]
I thought you might want a reference for the Sydney Olympics case

**Comment by sharronrush** [comment]
Closed to integrate with Issue #35
