### ISSUE TITLE
Minimize Legal Risk - first or last?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#21]
Please include perspectives on why we might want this section first or last. Please think about different environments - government, education, industry, small orgs, international orgs, etc. - noting that different countries have different legal environments.

**Comment by bakkenb** [comment]
In my opinion, which can be swayed by valid points, is the following order...
- Support Diversity and Inclusion
- Drive Innovation
- Minimize Legal Risk
- Align with Global Web Standards

Part of me thinks that it does not matter what order because the intended audience is those who are looking for guidance and language to help convince others in their organization that a11y is good business sense and should be implemented. 

But on the other hand, we may have business leaders visit this resource or be sent to this resource by others and the above order is what I would expect to see the drivers listed as.  Even though I might be more interested in minimizing legal risk or ROI, the article seems more sound when the first driver is about Diversity and Inclusion, and the second is innovation. Hopefully those are more important to companies in the long run than a hyper-prioritized need to minimize risk. 

Just my two cents. Okay with the order the group decides upon.

**Comment by hkramer** [comment]
I like Brent's order - it starts with the 2 most positive rationales.

**Comment by slhenry** [comment]
I think "Minimize Legal Risk" is a key driver for many situations. Obviously it's not for some.

(I think "Align with Global Web Standards" is overall the least compelling for many people.)

Therefore, I think "Minimize Legal Risk" should either be first or last.

I slightly lean towards last, since we would like for the others to be what really motivates people.

Last is also a strong place for it.

**Comment by lakeen** [comment]
I agree with the order Brent is proposing.

**Comment by vavroom** [comment]
I don't object to the order proposed by Brent, though my gut feeling is that "Minimize Legal Risks" should be first. While we want to encourage people to think about doing the right thing for the right reasons first, the cynical part of my brain can't help thinking that a large part, if not the majority, of Big Business will care primarily about the legal risk.

**Comment by kakinney** [comment]
I like Brent's order.  I don't think it should be first because I believe that if you give people the strong reasons you do, they will WANT to do it for the right reason for moving their business forward.  I think the legal risk should come if they truly can't see the business value, then they should do it so they don't end up in litigation.

**Comment by nrhsinclair** [comment]
Sharron's intro paragraph does a good job of laying out the drivers in a way that gives them similar to equal weight, ... "have been sorted here into a few broad categories" with that opening paragraph minimizing legal risk seems to work fine as the first driver listed, and the supporting items included under that heading are very strong reasons to include as first part of the persuasive argument ...  UN Convention on the Rights of Persons with Disabilities is a strong driver to include first.

**Comment by slhenry** [comment]
EOWG f2f proposed decision:
* Support Diversity and Inclusion
* Drive Innovation
* Align with Global Web Standards
* Minimize Legal Risk
