### ISSUE TITLE
Business Case for Accessibility

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-bcase#25]
I am unable to attend this week's meeting but I feel it important to present my thoughts on the two versions "story" and "bullet".   I was not aware that there was a second "bullet" version and thus, my recent feedback on the "story" version was based on the consideration of just one resource for the business case, not having looked at the other resource.  I apologize for this oversight.

To start, I'm not sure that I understand the need to have two versions.  I would frankly prefer to have just one version for the following reasons:

- the two versions contain **quite similar information** yet bear the same title "The Business Case for Accessibility".  They both cover "Innovation", "Brand enhancement", "Increase Market Research", "Financial and Legal Risk" except that the "bullet" version covers more, i.e., "Impacts Customer Satisfaction", "Supports Diversity and Inclusion", "Decreases Expenses" and provides examples. 
- the "story" version misses important examples presented per category unlike the bullet version where they are already sorted under the specific example.  I realize that there is a long list of examples at the bottom of the page of the "story" version but, as we all know, people just don't have the time to dissect the information and it's tedious (for me) to go through this list.  It's feels a bit too academic and I think we are moving away from the well-known usability practice of presenting information on the web so that the user can scan it.  Fond memories of "Don't make me think" - Steve Krug.
- I put myself in the end user's position, in a search, do I want to spend time reading two resources with quite similar content.  Which version should he/she go to? 
- On the web, we are fighting against time to win people over.  Thus, I'm always for getting to the point and finding the information I need fast.  I think the "bullet" version nicely splits this up.

If there was a choice between the two "story" and "bullet", I would **strongly prefer** the "bullet" version because it is "a one-stop" resource with ample pointers per subject to a variety of resources.  It gives a really complete picture for the business case covering several angles and benefits of accessibility and it is convincing.  I also really like the way the examples are presented with a short paragraph to explain the reasoning before listing the examples.  I am sure that the case studies described in the story version could be included in the "bullet" version.   In particular, the bullet version conveys a key point to support accessibility that **accessibility benefits everyone**.  (I just wonder if the nice descriptions given in the story version could possibly be added to the introductory paragraphs in the "bullet" version under each sub-heading.) 

**If it is important to have two versions**, then, the titles should be quite different and the story version could be more of an introduction to the evolving business case for accessibility, in which case I think it should be shorter and we could link to the complete bullet version from there.  

Finally, I will give my own personal experience.  When I needed to convince the Organization I previously worked for about introducing web accessibility, it was the WAI resource which gave many and diverse examples to support accessibility that won over the management.  Thus, I think it is really important to have a one-stop resource with supporting examples split into a number of subjects and the "bullet" version just does it.

**Comment by sharronrush** [comment]
Thanks Vicki for your extensive comments. I strongly agree that we want only one version of anything that we call "The Business Case" at WAI. 

After these months of research (I cannot count the number of articles I have read) and my own review  of the bulleted version, I strongly disagree however, that it is the best approach to reach the audience we identified - business leaders and advocates.  

I found  the bulleted version to be quite inconsistent with the business oriented articles that I have read for nearly a year. The vocabulary, the expand/collapse mechanism, and the unsubstantiated statements are not at all convincing to me and I can't see how they will convince many decision makers. Some of them may be useful to advocates in building their own case internally. That is why I suggested the ability to build their own bulleted presentation from a customizable template that we will create.

As currently formatted, the bulleted version presents some statements as fact with no attribution. They are then provided with "examples" from expandable sections with general statements that are not really  on point. I do not like expand/collapse in any case, If you do not expand the section you are left with unsubstantiated claims. And to use the expand, you must understand the page symbols and be willing to use them. In skimming you are not likely to do that.  As a result, I find that approach hard to read and process and generally difficult to follow logically. That is a personal preference I know. But here, as we try to build a convincing rationale for accessibility, the entire effect is jarring and not at all conducive to building a coherent "Case." 

So if your comments are "strong" as you said, it seems we need to meet and walk through them.  If you will not be there tomorrow, it will be at least another two weeks before that can be done.

**Comment by brewerj** [comment]
I'm unclear why this needs to be either/or; I think that there's a place for both formats, and that they may  be very good complements to each other. I'm very interested in the story-approach, including the direct reflections of C-level managers about the business value of accessibility. I think that there are some audiences for whom that approach is best, particularly if it can be done briefly, close to an "executive summary" one-pager that is likely to get picked up and skimmed by busy execs. 

I think though that the bulleted approach is useful for different audiences. I've had experiences similar to what Vicki describes scores of times over the years, where I walk through the resource with a manager (sometimes the sole initial accessibility proponent in a company) and we talk about which business case themes are most relevant for their organization. Most say that the resource is useful, including the details that go along with those themes, though yes, they all say that the business themes need to be updated, which I think the new bulleted outline is a good start on.  I agree that the expand/collapse functionality isn't the best option for this resource--but I see that as a formatting issue that can be overcome. 

I'm hoping that we might end up with complementary resources for this, because I think both approaches will be valuable, and may allow people from different parts or levels of an organization to find resources that support their different styles of understanding and working on a business case for their organization.

**Comment by sharronrush** [comment]
I think the telling phrase here is "over the years." What may have been useful ten years ago is less effective for the modern decision maker. As I took on this task, I surveyed far and wide, asking people "Do you use the business case on WAI? No one said yes unequivocally. Several said they would never refer a client or a boss to the resource because it was so dense, hard to read, and text-heavy with few calls to action or actual examples of accessibility in action.  Many eye-rolls accompanied any introduction of the previous version of the Business Case. Our stated goal was to tell a story that would resonate as is.  I have no problem with creating a supplemental resource. In fact that is in my project plan. But to ask EO at this time to split focus between two competing "documents" and to consider an alternative approach this late in game seems counter productive. My preference is to get his published (it is not the Holy Grail after all and can be changed at any time). Put it out in the world and see what people say they need to augment the story and the resources that are offered.

**Comment by slhenry** [comment]
I'm also thinking that we probably don't want two "versions" of essentially the same information.

I see how the "story edition" works well for some audiences
and the "bullet edition" works well for some audiences.

A brainstorm idea:
* "Exploring the Business Case" is the story edition with the current approach and tone (including footnotes -- I'll comment on that separately)
* "Business Case Summary" (or "At-a-Glance" to match other WAI resources) - has *just* the headings and short paragraph from the bullet edition -- no expand-collapse examples. 
* "Resources for the Business Case" is a separate page that both point to.
* Template (if that pans out)

**Comment by brewerj** [comment]
Sorry if my earlier comment wasn't clear -- the interactions I describe are recent and current, not only in the past. Particularly when I'm talking with individuals and organizations newer to accessibility, a business case is one of the topics that people most ask for; they're glad to learn that we have a resource for this; and yes they think it needs updating. I appreciate the work to update it. I also don't know if there's a single approach (e.g., story-only, or bullets-only), that best speaks to the needs of every audience, so perhaps having different views/pages of the resource might be useful. Would be interesting to keep getting feedback on that.

**Comment by bakkenb** [comment]
After sufficient EOWG discussion <[minutes](https://www.w3.org/2018/07/27-eo-minutes.html#item03)>, it was determined that only one resource should be published. The majority of the working group participating in the call favored the "story" version of the business case, wanted to complete it, and get it published. Once published, the group is interested in looking at metrics/analytics, and gathering other feedback for future improvement if needed.

Sharron will continue to work on the current version and is open for comments in GitHub. She will take and work in key comments provided in the 27 July meeting.

**Comment by bakkenb** [comment]
@vmmiller - Thank you for your original comments. I would like to see if we can get some or most of your concerns addressed with the current version that Sharron has been working on. 

Would like to leave this issue open until that happens. 

I have asked Sharron to get with you Vicki to discuss and see what tweaks can be made to the current draft so that you can support its publication in time.

**Comment by sharronrush** [comment]
Hi Vicki and Judy,

I am all in favor of getting this work in progress finished, published and getting feedback from the community about what additional resources they need.  I think a one page summary or bulleted edition might be very useful. We may also consider a previously suggested idea to create a slide template that people can customize for their own environment.  My hesitation about working on two versions at the same time is one of focus. I have not been able to get the attention of the group to contribute to one resource - I am not confident about asking for thorough review and thoughtful comments when putting two resources in front of them.  

That said, I am very interested in Vicki's comment that "..the "bullet" version covers more, i.e., "Impacts Customer Satisfaction", "Supports Diversity and Inclusion", "Decreases Expenses" and provides examples." Let's unpack these one by one and see how we might incorporate the points into the story version in a way that satisfies this concern. I want to be cautious however to avoid making claims that undermine our credibility. Our previous Business Case was criticized for making unsubstantiated claims and providing  "examples" that do not really tell the whole story or that make claims for accessibility that were in fact shared by other design approaches. I would like all of our points and examples to be fully documented. 

If it is OK with you, I would like to close this issue and open 3 new ones with the specific question of how to address each of your points that are not sufficiently addressed in the narrative version.

Then, with everyone's permission, I will also open one to ask about peripheral resources to support the Business Case article assuming that we are going with the narrative version. That way, we can keep these issues separate and clear. If anyone objects, please re-open of course.
