### ISSUE TITLE
Title/Name

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-bcase#3]
Current title: [Developing a Web Accessibility Business Case for Your Organization](https://www.w3.org/WAI/bcase/)

one recent brainstorm:
> Building a Business Case

I remember that we considered this previously and ruled it out because it sounded like you had to make up a business case.

Of the top of my head, another brainstorm might be along the lines of:
> Explaining the Business Case

It would be good to pull up the past title discussions to see what we learn from them now. :-)

**Comment by sharronrush** [comment]
I have looked through the title discussions, thanks for that suggestion. 

How about something really simple like 
    The Business Case for Accessibility

**Comment by slhenry** [comment]
*Might* be the best approach. Partly depends on the revised resource. 

A big issue is that the business case is **really different** for different organizations in different situations.

The previous resource was meant to provide a "cafeteria plan" approach, and guide people to use the resource to develop a case specifically for their particular organization.

See also [Audience - direct primary, and usually indirect important](https://github.com/w3c/wai-)bcase/issues/2

I'm not sure if the editors are proposing a totally different approach to this resource. I guess we'll need to wait and see :-)

**Comment by sharronrush** [comment]
I think it was true at one time that the business case was quite different from one industry or organization size to the next. But it really doesn't seem that way out in here in the filed any more.  Legal requirements and expectations are clearly expanded beyond government/government funded only. Market pressures from aging populations are felt universally. Even here today doing training for a higher ed testing institution, I tried to skip quickly through a few of the market forces slides since in the past I had been told by this group that our population is not impacted by general aging stats.  But they are rethinking that due to career changes and returning vets.

**Comment by sharronrush** [comment]
My point is just that the differences are far less profound than they once were

**Comment by bakkenb** [comment]
Please read [renaming discussion from 01 September 2017 Meeting](https://www.w3.org/2017/09/01-eo-minutes.html#item03) prior to adding more to this thread.

**Comment by dboudreau** [comment]
Making the business case for accessibility seems like the best title to me. Straightforward, and it announces exactly what we can expect from the resource.

**Comment by yatil** [comment]
“Making your business case”?

(I think as long as “business case” is in there, it probably doesn’t matter too much. Nobody is expecting a diagram “Accessibility --> ????? --> $$$$” in there. It feels natural that this page has different considerations.)

**Comment by nitedog** [comment]
I like all "Building a Business Case", "Explaining the Business Case", and "Making the Business Case". All three highlight that it is *not* one single business case for all industries and geographic regions, but that it needs to be build, made, or explained based on the arguments provided in the resource.

**Comment by slhenry** [comment]
I'm still a little concerned that "Making the Business Case" could come across like you have to make it up, because there isn't a case for it. However, if others have considered that point and don't think it's a problem, I'm OK with it.

**Comment by bakkenb** [comment]
I do not like "building" or "making" because the resource does not help you literally build or create a business case. The resource helps some understand why accessibility integration is good business sense, and it helps others by providing language that can be used by advocates to put forth a solid business case for implementing accessibility in everything the organization is doing. 

If the resource is tersified, as @dboudreau suggests (/me +1), then the resource can serve a third purpose of organizational leaders looking at it to be persuaded of all the reasons accessibility is important (morally, financially, brand, growth, etc...). The current length of content will not be tolerated by upper management as it is to unwieldy to consume.

Back to the name. I prefer "The Business Case" or "Business Case" as this seems to be **_our_** business case for implementing accessibility work. In other words, "Here is our business case, take it, use it, steal from it, do what you need to do to get accessibility efforts going in your organization!"

**Comment by dboudreau** [comment]
How about "defining the business case for accessibility", then?

**Comment by hkramer** [comment]
I go with "The Business Case for Web Accessibility." It's vague enough so that it covers all the resources under that area and specific enough so that people would have a good sense of it's purpose. I could also see adding "Making" in front. I don't a consensus forming on this one.

**Comment by slhenry** [comment]
(I think it is a given that this will be tersified. As I understand it, Sharron's current vision is for a short "executive summary"-type page or section (that even high-level folks might read) -- then separately more details for those who want it, for example, advocates within an organization who want to write up a specific business case with the elements that will resonate in their specific organizational environment. I support that approach.)

Seems we have a disconnect on what this is and what it intends to be.

This resource is not presenting a business case that works for all organizations -- that's not possible. It's not our business case for W3C either. There are lots of things in there that we wouldn't have for a W3C/WAI business case.

This resource does help you write up a business case specific for your organization. It provides a bunch of ideas, and specific guidance on what to include, e.g., in [Developing a Customized Business Case](https://www.w3.org/WAI/bcase/#custom) and in the "[Identifying...](https://www.w3.org/WAI/bcase/soc#custom)" section of each sub-page. The intention is that someone could take this as a starting point, and then delete the info that's not a strong argument for their organization - and *boom* you have a customized business case for your org. You can add more details, but don't have to.

Therefore, I am fairly hesitant to title this resource "The Business Case for Web Accessibility". That makes it seem like there is one business case, and that's not the case. And I think it's important for advocates to understand that they need to figure out which elements are strongest in their org, and stress those -- not just take anything we or anyone else gives them and assume ti will work well in their org. 

Are we sure we don't want to stick with existing title: "Developing a Web Accessibility Business Case for Your Organization"?

I'm OK with Denis's last suggestion of "Defining the Business Case for Accessibility"

Whatever we go with, I am fine with just "Business Case" in the nav.

**Comment by slhenry** [comment]
@sharronrush "I have looked through the title discussions"

Could you put links to minutes (& surveys or emails if there, too) so we can skim them?

**Comment by bakkenb** [comment]
Thank you Shawn for this explanation. This really helps me understand the intent of the resource. It is not clear from the overview opening paragraphs really what this resource is for. You have explained it very well in your comment. Would like to have some of that, in a nutshell, on the page to help everyone understand what the page(s) are for.

With your explanation, another idea for title could be "Elements for an Accessibility Business Case."

**Comment by slhenry** [comment]
+1 for better explanation in the resource itself!

**Comment by slhenry** [comment]
Please read [meeting survey](https://www.w3.org/2002/09/wbs/35532/eo7Sept/results#xtopic) results.

**Comment by sharronrush** [comment]
Closing this issue with the resolution to call the resource: The Business Case for Accessibility
with a subtitle: Accessibility is Good Business
